/* Generated by gencube.py -- do not edit. */

#define CUBE_ROWS 13
#define CUBE_COLS 23

struct cube_run {
	unsigned char len;
	unsigned char face;	/* 0 top, 1 left, 2 right */
	unsigned char r, g, b;
	const char *ch;		/* NULL for a gap */
};

static const struct cube_run cube_r0[] = {
	{ 8, 0, 0, 0, 0, NULL },
	{ 2, 0, 226, 232, 238, "▄" },
	{ 2, 0, 226, 232, 238, "█" },
	{ 2, 0, 226, 232, 238, "▄" },
	{ 9, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r1[] = {
	{ 4, 0, 0, 0, 0, NULL },
	{ 2, 0, 217, 224, 230, "▄" },
	{ 2, 0, 217, 224, 230, "█" },
	{ 6, 0, 209, 217, 225, "█" },
	{ 2, 0, 217, 224, 230, "█" },
	{ 2, 0, 217, 224, 230, "▄" },
	{ 5, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r2[] = {
	{ 2, 0, 208, 216, 223, "▄" },
	{ 2, 0, 208, 216, 223, "█" },
	{ 14, 0, 198, 207, 216, "█" },
	{ 2, 0, 208, 216, 223, "█" },
	{ 2, 0, 208, 216, 223, "▄" },
	{ 1, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r3[] = {
	{ 1, 1, 139, 148, 157, "█" },
	{ 1, 1, 114, 125, 136, "█" },
	{ 18, 0, 187, 197, 207, "█" },
	{ 1, 2, 50, 56, 63, "█" },
	{ 1, 2, 87, 92, 98, "█" },
	{ 1, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r4[] = {
	{ 1, 1, 134, 143, 152, "█" },
	{ 4, 1, 108, 118, 129, "█" },
	{ 12, 0, 176, 187, 197, "█" },
	{ 4, 2, 47, 53, 59, "█" },
	{ 1, 2, 84, 89, 94, "█" },
	{ 1, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r5[] = {
	{ 1, 1, 130, 138, 146, "█" },
	{ 8, 1, 102, 112, 122, "█" },
	{ 4, 0, 165, 177, 188, "█" },
	{ 8, 2, 44, 49, 55, "█" },
	{ 1, 2, 82, 86, 91, "█" },
	{ 1, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r6[] = {
	{ 1, 1, 124, 132, 141, "█" },
	{ 10, 1, 95, 105, 116, "█" },
	{ 10, 2, 40, 46, 51, "█" },
	{ 1, 2, 79, 84, 88, "█" },
	{ 1, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r7[] = {
	{ 1, 1, 119, 127, 135, "█" },
	{ 10, 1, 89, 99, 109, "█" },
	{ 10, 2, 37, 42, 47, "█" },
	{ 1, 2, 76, 80, 84, "█" },
	{ 1, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r8[] = {
	{ 1, 1, 114, 121, 130, "▀" },
	{ 2, 1, 114, 121, 130, "█" },
	{ 8, 1, 83, 92, 102, "█" },
	{ 8, 2, 33, 38, 43, "█" },
	{ 2, 2, 73, 77, 81, "█" },
	{ 1, 2, 73, 77, 81, "▀" },
	{ 1, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r9[] = {
	{ 3, 0, 0, 0, 0, NULL },
	{ 2, 1, 109, 116, 124, "▀" },
	{ 2, 1, 109, 116, 124, "█" },
	{ 4, 1, 77, 86, 95, "█" },
	{ 4, 2, 30, 35, 39, "█" },
	{ 2, 2, 70, 75, 78, "█" },
	{ 2, 2, 70, 75, 78, "▀" },
	{ 4, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r10[] = {
	{ 7, 0, 0, 0, 0, NULL },
	{ 2, 1, 104, 111, 118, "▀" },
	{ 2, 1, 104, 111, 118, "█" },
	{ 2, 2, 68, 71, 75, "█" },
	{ 2, 2, 68, 71, 75, "▀" },
	{ 8, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r11[] = {
	{ 23, 0, 0, 0, 0, NULL }
};
static const struct cube_run cube_r12[] = {
	{ 23, 0, 0, 0, 0, NULL }
};

static const struct cube_run *const cube_rows[CUBE_ROWS] = {
	cube_r0, cube_r1, cube_r2, cube_r3, cube_r4, cube_r5, cube_r6, cube_r7, cube_r8, cube_r9, cube_r10, cube_r11, cube_r12
};
static const unsigned char cube_nruns[CUBE_ROWS] = {
	5, 7, 6, 6, 6, 6, 5, 5, 7, 8, 6, 1, 1
};
