import math, sys

CELL = 0.60 / 1.34          # column width as a fraction of one row
HW   = 11                    # half-width in columns; 23 wide, ~12 rows
RUN  = HW * CELL
R    = RUN * math.tan(math.radians(30))
SH   = math.hypot(RUN, R)

A=(HW,0.0); B=(2*HW,R); C=(2*HW,R+SH); D=(HW,2*R+SH); E=(0.0,R+SH); F=(0.0,R); G=(HW,2*R)
FACES={"top":[A,B,G,F],"right":[B,C,D,G],"left":[F,G,D,E]}
FACE_ID={"top":0,"left":1,"right":2}
def inside(pt,poly):
    x,y=pt;n=len(poly);ins=False
    for i in range(n):
        x1,y1=poly[i];x2,y2=poly[(i+1)%n]
        if (y1>y)!=(y2>y):
            if x < x1+(y-y1)*(x2-x1)/(y2-y1): ins=not ins
    return ins
def face_at(x,y):
    for n,p in FACES.items():
        if inside((x,y),p): return n
RAMP={"top":((0xdc,0xe3,0xea),(0x9e,0xaa,0xb6)),
      "left":((0x73,0x7e,0x89),(0x3e,0x46,0x4f)),
      "right":((0x33,0x39,0x40),(0x16,0x1a,0x1e))}
EXT={n:(min(p[1] for p in poly),max(p[1] for p in poly)) for n,poly in FACES.items()}
W=2*HW+1; H=int(math.ceil(2*R+SH))+1
grid=[[None]*W for _ in range(H)]
for r in range(H):
    for c in range(W):
        up=face_at(c+0.5,r+0.25); lo=face_at(c+0.5,r+0.75)
        grid[r][c]=("█",up) if (up and lo) else (("▀",up) if up else (("▄",lo) if lo else (None,None)))
def lerp(a,b,t): return tuple(round(x+(y-x)*t) for x,y in zip(a,b))
def colour(r,c):
    ch,f=grid[r][c]
    if f is None: return None
    y0,y1=EXT[f]; t=min(1.0,max(0.0,(r-y0)/max(0.001,y1-y0)))
    base=lerp(*RAMP[f],t)
    rim=False
    for dr,dc in ((0,1),(0,-1),(1,0),(-1,0)):
        a,b=r+dr,c+dc
        nf=grid[a][b][1] if 0<=a<H and 0<=b<W else None
        if nf is None: rim=True;break
    return (lerp(base,(0xff,0xff,0xff),0.18) if rim else base), FACE_ID[f]

out=[]
out.append("/* Generated by scratchpad/gencube.py -- do not edit by hand. */")
out.append("/* An isometric cube, half-row sampled. Proportions derive from the")
out.append(" * character cell's aspect (a column is ~0.45 of a row): dropping half a")
out.append(" * row per column would give a 48-degree edge where isometric wants 30,")
out.append(" * and the solid comes out stretched. The rim lights the OUTER silhouette")
out.append(" * only -- lighting the seams between faces splits it into three shapes. */")
out.append("")
out.append("#define CUBE_ROWS %d" % H)
out.append("#define CUBE_COLS %d" % W)
out.append("")
out.append("struct cube_run { unsigned char len, face; unsigned char r, g, b; const char *ch; };")
out.append("")
rows=[]
for r in range(H):
    runs=[]; cur=None
    for c in range(W):
        ch,f=grid[r][c]
        key=(ch,)+ (colour(r,c) or (None,None))
        if cur and cur[0]==key: cur[1]+=1
        else:
            if cur: runs.append(cur)
            cur=[key,1]
    if cur: runs.append(cur)
    items=[]
    for (ch,rgb,face),n in runs:
        if ch is None: items.append('{ %d, 0, 0, 0, 0, " " }' % n)
        else: items.append('{ %d, %d, %d, %d, %d, "%s" }' % (n, face, rgb[0], rgb[1], rgb[2], ch))
    rows.append("\tstatic const struct cube_run r%d[] = { %s };" % (r, ", ".join(items)))
out.append("/* One array per row, then a table of them: keeps each row's runs adjacent. */")
out.append("static const struct cube_run *const cube_row[CUBE_ROWS];")
open("cube_gen.txt","w").write("\n".join(out))
# emit the real header
hdr=["/* Generated by gencube.py -- do not edit. */","",
     "#define CUBE_ROWS %d" % H, "#define CUBE_COLS %d" % W, "",
     "struct cube_run {","\tunsigned char len;","\tunsigned char face;\t/* 0 top, 1 left, 2 right */",
     "\tunsigned char r, g, b;","\tconst char *ch;\t\t/* NULL for a gap */","};",""]
for r in range(H):
    runs=[]; cur=None
    for c in range(W):
        ch,f=grid[r][c]
        col=colour(r,c)
        key=(ch,)+(col if col else (None,None))
        if cur and cur[0]==key: cur[1]+=1
        else:
            if cur: runs.append(cur); 
            cur=[key,1]
    if cur: runs.append(cur)
    items=[]
    for (ch,rgb,face),n in runs:
        if ch is None: items.append("{ %d, 0, 0, 0, 0, NULL }" % n)
        else: items.append('{ %d, %d, %d, %d, %d, "%s" }' % (n, face, rgb[0], rgb[1], rgb[2], ch))
    hdr.append("static const struct cube_run cube_r%d[] = {\n\t%s\n};" % (r, ",\n\t".join(items)))
hdr.append("")
hdr.append("static const struct cube_run *const cube_rows[CUBE_ROWS] = {")
hdr.append("\t" + ", ".join("cube_r%d" % r for r in range(H)))
hdr.append("};")
hdr.append("static const unsigned char cube_nruns[CUBE_ROWS] = {")
lens=[]
for r in range(H):
    n=0; cur=None
    for c in range(W):
        ch,f=grid[r][c]; col=colour(r,c)
        key=(ch,)+(col if col else (None,None))
        if cur!=key: n+=1; cur=key
    lens.append(n)
hdr.append("\t" + ", ".join(str(x) for x in lens))
hdr.append("};")
open("cube.h","w").write("\n".join(hdr)+"\n")
print("cube.h: %d rows x %d cols, %d runs total" % (H,W,sum(lens)))
