# adduser(8) and rmuser(8) for NextBSD: the familiar prompts, driving
# dscli(8) to create and remove directory users (E18 U9,
# nextbsd/nextbsd-userland#255).

SCRIPTS=	adduser.sh rmuser.sh
SCRIPTSDIR=	/usr/sbin
MAN=		adduser.8 rmuser.8

.include <bsd.prog.mk>
